[build]
  command = "npx expo export --platform web"
  publish = "dist"

[[redirects]]
  from = "/tree"
  to = "/index.html"
  status = 200
  force = true
  query = {userName = ":userName"}

[build.environment]
  NODE_VERSION = "18"